cmake_minimum_required(VERSION 3.29)
project(yonsei_oop)

set(CMAKE_CXX_STANDARD 20)

add_executable(yonsei_oop
        assignment-1/problem2.cpp
        assignment-1/problem1.cpp
        assignment-1/problem1_extra.cpp
        playground/point.cpp
        playground/hot-dog-stands.cpp
        playground/P8-1.cpp
        playground/P8-2.cpp
        playground/P8-3.cpp
        playground/P8-5.cpp
        playground/test.cpp
        midterm-exam.cpp
        final-exam.cpp
        assignment-2/problem_1/problem1.cpp
        assignment-2/problem_2/problem2.cpp
        final-exam.cpp
        pointer.cpp
        multiple-files/main.cpp
        multiple-files/hello_world.cpp
        multiple-files/hello_world.h)
